# ARPABET PHONEME MAPPING
# DO NOT CHANGE
# This overwrites the phonetics.py file.

CKPT_DIR = "./checkpoints"

WINDOW_SIZE = 9
NUM_ACOUSTIC_PARAMETERS = 25
NUM_PHONEME_LOGITS = 42

TRAIN_BATCH_SIZE = 64
TEST_BATCH_SIZE = 256

LR = 1e-5
WEIGHT_DECAY = 1e-4
NUM_EPOCHS = 1000
